### ISSUE TITLE
C-style line comment in scaffolding manifest.json?

### ISSUE THREAD

**Issue by eyalroz** [cleidigh/ThunderStorm#1]
In:
https://github.com/cleidigh/ThunderStorm/blob/master/examples/scaffolds/tb-mail-ext-bare/manifest.json

there's a line beginning with `//`. Is that intentional? Is that valid? Even if it is - it merits some explanation.

**Comment by cleidigh** [comment]
@eyalroz 
Good observation, and does to serve for comment (pun intended)

The Web/Mail Extensions manifest.json is allowed to be in either straight json or json(c) which allows for comments in JavaScript format.  I will add a comment and have Ryan do the same in the tutorial.

**Comment by cleidigh** [comment]
Addressed with file comment.
Need to add to tutorial
